on:
    push:
      branches:
        - main
env:
        MYNAME: "Chandra"
        MYCITY: "Hyderabad"

jobs:
    helloOne:
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v3
        - name: execute a command
          run: echo "Hello, world!" && echo {{ env.MYNAME }} from {{ env.MYCITY }}
