on:
    push:
      branches:
        - main
jobs:
    helloOne:
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v3
        - name: execute a command
          run: echo "Hello, world!"