name: E2E Tests
on: [push, pull_request, workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
            - name: Install dependencies
              run: npm ci
            - name: Run Chrome tests
              run: npm run test:chrome
            - name: Run Firefox tests
              run: npm run test:firefox